package com.exercise.aucta_exercise.model;

public enum Genre {
    ACTION,
    ADVENTURE,
    COMEDY,
    DRAMA,
    HORROR,
    ROMANCE,
    SCIENCE_FICTION,
    THRILLER,
    FANTASY,
    ANIMATION,
    DOCUMENTARY,
    CRIME,
    MYSTERY,
    WAR,
    WESTERN,
    MUSICAL,
    FAMILY,
    HISTORY,
    SPORT,
    BIOPIC,
    SUPERHERO,
    SUSPENSE,
    NOIR,
    PSYCHOLOGICAL,
    MUSIC,
    EXPERIMENTAL,
    SHORT_FILM,
    FOREIGN,
    LGBTQ,
    TEEN,
    CHRISTMAS,
    PARODY,
    SATIRE
}
